[build]
  publish = "."
  functions = "netlify/functions"
  command = "npm install"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "nft"
  external_node_modules = ["@netlify/blobs", "@netlify/functions"]

[functions."schedule-cron"]
  schedule = "0 * * * *"

[functions."weekly-cron"]
  schedule = "0 6 * * 1"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
